name: Run e2e tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      version:
        description: run manually
        default: v1.0.0
        required: true
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
#    - run: npm install
    
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      uses: ianwalter/puppeteer-container@afefc4bee7341a77baa94503da684e2895ea5d30
      with:
        args: npm install
    - name: Test
      uses: ianwalter/puppeteer-container@afefc4bee7341a77baa94503da684e2895ea5d30
      with:
        args: npm start
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: logs
        path: logs
#    - run: npm start
