name: Run e2e tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      version:
        description: run manually
        default: v1.0.0
        required: true
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - uses: nanasess/setup-chromedriver@master
      with:
       chromedriver-version: '89.0.4389.130'
    - run: chromedriver
    
    - run: npm install
    
    - run: npm start

